language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'
matrix:
    fast_finish: true
    allow_failures:
        - php: '7.0'

services:
    - mysql

before_script:
    - mysql -e "create database IF NOT EXISTS symfony" -uroot;
    - composer self-update
    - composer install --dev

script: phpunit --configuration phpunit.xml.dist

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
