#!/usr/bin/env bash

rm -fR var/cache/
rm -fR var/logs/
rm -fR var/sessions/
mkdir var/sessions/
rm -fR web/uploads
mkdir web/uploads
php bin/console assets:install
chmod -R 0777 var/cache/
chmod -R 0777 var/logs/
chmod -R 0777 var/sessions/
chmod -R 0777 web/uploads
gulp --type=production
